name: Deploy Website

on: 
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Build Image
        run: "docker build -t pipedream_website ."
        working-directory: ./client
      - name: Remove Running Image, if exists
        run: "docker rm -f pipedream_website || true"
        working-directory: ./client
      - name: Run Image
        run: "docker run -p 17000:17000 -d --name pipedream_website pipedream_website"
        working-directory: ./client
      
