name: Deploy Lobby Service

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Remove Image, if exists
      run: "docker rm -f pipedream_lobby_service || true"
    - name: Build Image
      run: "docker build -t pipedream_lobby_service ."
    - name: Run Image
      run: "docker run -p 5080:5080 -d --name pipedream_lobby_service pipedream_lobby_service"
      
